### ISSUE TITLE
Runtime Panic

### ISSUE THREAD

**Issue by edoardottt** [hakluke/hakrawler#86]
- command: `cat all2.txt | httprobe | hakrawler -plain > chain.txt`
- version: `beta11`
```
panic: runtime error: slice bounds out of range [:4125] with capacity 4096

goroutine 19642 [running]:
bufio.(*Writer).Flush(0xc0002bc7c0, 0xc000a8e420, 0x1d)
	/usr/lib/go-1.14/src/bufio/bufio.go:591 +0x1c0
bufio.(*Writer).Write(0xc0002bc7c0, 0xc000a8e420, 0x28, 0x30, 0x28, 0x30, 0xc002938b60)
	/usr/lib/go-1.14/src/bufio/bufio.go:627 +0xfa
github.com/hakluke/hakrawler/pkg/collector.(*Collector).colorPrint(0xc002d6df50, 0xb42f80, 0xc00137ffc0, 0xc000a8e390, 0x27, 0x1)
	/home/edoardottt/go/src/github.com/hakluke/hakrawler/pkg/collector/collector.go:406 +0x612
github.com/hakluke/hakrawler/pkg/collector.(*Collector).recordIfInScope(0xc002d6df50, 0xb42f80, 0xc00137ffc0, 0xc000426de0, 0x19, 0xc000a8e390, 0x27, 0xc0021ca5e0, 0x0)
	/home/edoardottt/go/src/github.com/hakluke/hakrawler/pkg/collector/collector.go:293 +0x1e0
github.com/hakluke/hakrawler/pkg/collector.(*Collector).parseRobots(0xc002d6df50, 0xc000426de0, 0x19, 0xc0021ca5e0)
	/home/edoardottt/go/src/github.com/hakluke/hakrawler/pkg/collector/collector.go:351 +0x4d1
github.com/hakluke/hakrawler/pkg/collector.(*Collector).Crawl.func1(0xc002c9f6d0, 0xc002d6df50, 0xc000426de0, 0x19, 0xc0021ca5e0)
	/home/edoardottt/go/src/github.com/hakluke/hakrawler/pkg/collector/collector.go:151 +0x75
created by github.com/hakluke/hakrawler/pkg/collector.(*Collector).Crawl
	/home/edoardottt/go/src/github.com/hakluke/hakrawler/pkg/collector/collector.go:149 +0x2b1
```

**Comment by hakluke** [comment]
Fixed in v2
